alias chpc='ssh dmartin@lengau.chpc.ac.za'
alias chpcx='ssh -X dmartin@lengau.chpc.ac.za'
alias viz='ssh -f dmartin@lengau.chpc.ac.za -L 5914:chpcviz1:5914 -N'
alias cpp='docker run -i cpp'
alias vim='nvim'
alias ls='ls -l --color=auto'
alias lsa='ls -la --color=auto'
